services:
  uc-intg-wholphin:
    build: .
    container_name: uc-intg-wholphin
    network_mode: host
    volumes:
      - </path/to/config>:/config
    environment:
      - UC_INTEGRATION_HTTP_PORT=9090
      - UC_CONFIG_HOME=/config
      - PYTHONPATH=/app
    restart: unless-stopped
